blank_issues_enabled: false
contact_links:
  - name: Community
    url: https://github.com/CodewithAloha/discussions
    about: Start or join a conversation
  - name: Contact
    url: https://www.meetup.com/code-for-hawaii/messages/boards/?forum=20522315&op=ask_about_forums
    about: Contact us
